"""Concrete equity-state and European-option contract semantics for M1."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from enum import StrEnum
from typing import cast

from qf_platform._validation import calendar_date, nonnegative_finite_real
from qf_platform.pricing.cashflows import CashFlow, CashFlowStream
from qf_platform.pricing.state import StatePath


@dataclass(frozen=True, slots=True)
class EquityState:
    """Valuation-ready modeled equity state.

    ``spot`` is a modeled current spot level, not an observed quote/provenance
    container. Zero is admitted as the degenerate GBM boundary; negative and
    non-finite values are not.
    """

    spot: float

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "spot",
            nonnegative_finite_real(self.spot, name="spot"),
        )


@dataclass(frozen=True, slots=True)
class EquityStateSpace:
    """Non-negative finite spot state space used by the M1 equity law."""

    def contains(self, value: object, /) -> bool:
        return isinstance(value, EquityState)


class OptionRight(StrEnum):
    """European option exercise right."""

    CALL = "call"
    PUT = "put"


def _require_option_right(value: object) -> OptionRight:
    if not isinstance(value, OptionRight):
        msg = "right must be an OptionRight"
        raise TypeError(msg)
    return value


@dataclass(frozen=True, slots=True)
class EuropeanOption:
    """Immutable European call/put terminal-cash-flow contract."""

    expiry: date
    strike: float
    right: OptionRight

    def __post_init__(self) -> None:
        object.__setattr__(
            self,
            "expiry",
            calendar_date(self.expiry, name="expiry"),
        )
        object.__setattr__(
            self,
            "strike",
            nonnegative_finite_real(self.strike, name="strike"),
        )
        object.__setattr__(
            self,
            "right",
            _require_option_right(cast(object, self.right)),
        )

    def cash_flows(
        self,
        path: StatePath[date, EquityState],
        /,
    ) -> CashFlowStream[date]:
        """Return the single terminal option payoff generated by ``path``."""

        terminal_spot = path.value_at(self.expiry).spot
        if self.right is OptionRight.CALL:
            amount = max(terminal_spot - self.strike, 0.0)
        else:
            amount = max(self.strike - terminal_spot, 0.0)
        return CashFlowStream((CashFlow(self.expiry, amount),))
